### ISSUE TITLE
recommended practice for editing documentation pages

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-documentation-jekyll-skeleton#15]
I was reviewing our guidance for our documentation pages **Editing online in GitHub**. The last bullet explicitly calls out to "Commit directly to the gh-pages branch". 

When I give advice to folks on editing pages, I instruct them to:

> * As best practice, it's typically good to select "Create a new branch for this commit and start a pull request". No need to worry about what you call the branch. Then, click "Propose changes". This gives folks who are monitoring the repo an opportunity to review the changes and provide comments. Typically it's catching typos/markup issues. 
> * Another option is to "Commit directly to the gh-pages branch". This simply merges your changes directly into the file without review.

How do you feel about this change to our guidance @mwengren ?

https://github.com/ioos/ioos-documentation-jekyll-skeleton/blob/13713fed4af8d227f9ce155894d932bfe7c50635/_docs/howto.md?plain=1#L84

I don't want to overcomplicate things but it would be beneficial to have some review process for more significant changes to our docs.

**Comment by mwengren** [comment]
Sounds reasonable to me.   PRs are helpful most of the time.
