### ISSUE TITLE
sync_theme action was disabled

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-documentation-jekyll-skeleton#18]
@ocefpaf how do we ensure the action doesn't disable again?

**Comment by MathewBiddle** [comment]
Found it:

https://github.com/ioos/ioos-metadata/blob/df9c850908218739aeae326f5aa6c906769e3206/.github/workflows/sync_theme.yml#L42-L49

**Comment by ocefpaf** [comment]
We should send that bit of code to all repositories. I did ioos-metadata as a test case and it seem that it worked, right?

**Comment by MathewBiddle** [comment]
it did! https://github.com/ioos/ioos-metadata/actions

> We should send that bit of code to all repositories

Yes. I just did for the ioos-atn-data repo https://github.com/ioos/ioos-atn-data/tree/main/.github/workflows

**Comment by ocefpaf** [comment]
I'll try to get to the rest of them. BTW, we should be using the new syntax in https://github.com/ioos/ioos-metadata/pull/46

**Comment by ocefpaf** [comment]
@MathewBiddle I updated these so far:

- [X] https://github.com/ioos/glider-dac/pull/354
- [X] https://github.com/ioos/erddap-gold-standard/pull/74
- [X] https://github.com/ioos/mbon-docs/pull/54
- [X] https://github.com/ioos/ncei-archiving-cookbook/pull/7
- [X] https://github.com/ioos/conventions-for-observing-asset-identifiers/pull/2
- [X] https://github.com/ioos/ioos-atn-data/pull/81
- [X] https://github.com/ioos/ioos-documentation-jekyll-skeleton/pull/19
- [X] https://github.com/ioos/ioos.github.io/pull/9
- [X] https://github.com/ioos/BioData-Training-Workshop/pull/34
- [X] https://github.com/ioos/passive-acoustics/pull/5
